name: davidtemple
favicon: null
layout_spectrum: 0.24939
typography_spectrum: 0.49958
title: davidtemple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#2862c6'
    - '#86bae9'
    - '#f0e0c9'
    - '#618e4e'
  brandStrength: 0.05195815092884004
  lightness: 0.75
  saturation: 0.985025143250823
  rhythmicContrast: 1
purpose: []
